import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import styles from "@/styles/Home.module.css";
import About from "./about";
import Slider from "@/components/Slider";
import Navbar from "@/components/NavBar";


export default function Home() {
  return (
    <>
      <Head>
        <title>Callista Chan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainContainer}>
        <main className={styles.container}>
          <div className={styles.mainHeader}>
          <h1 className="home">Callista Chan</h1>
          <h2 className={styles.roles}>UX/UI Designer | Graphic Designer</h2>
          </div>
          <div className={styles.Links}>
          <Link className={styles.about} href="/about"> About </Link>
          <Link className={styles.projects} href="/projects"> My Work </Link>
          </div>
        </main>
        <footer>
        </footer>
      </div>

      <Slider />
    </>
  );
}
