import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import styles from "@/styles/Home.module.css";
import About from "./about";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <div className={styles.mainHeader}>
          <h1 className="home">Callista Chan</h1>
          </div>
          <div className={styles.Links}>
          <Link className={styles.about} href="/about"> About </Link>
          <Link className={styles.projects} href="/projects"> My Work </Link>
          </div>
          <h2 className={styles.warning}>This Portfolio is a Work in Progress!</h2>
        </main>
        <footer>
        </footer>
      </div>
    </>
  );
}
